import {
  type ReactNode,
  createContext,
  createElement,
  useContext,
  useEffect,
  useState,
} from "react";
import { AssetType } from "../backend";

export interface MarketAsset {
  name: string;
  displayLabel: string;
  type: AssetType;
  price: number;
  prevPrice: number;
  change24h: number;
  isForexRate: boolean;
}

const SEED: MarketAsset[] = [
  // ── CRYPTO – Binance listed coins (150+) ──────────────────────────────────
  {
    name: "BTC",
    displayLabel: "Bitcoin",
    type: AssetType.crypto,
    price: 68500,
    prevPrice: 68500,
    change24h: 2.5,
    isForexRate: false,
  },
  {
    name: "ETH",
    displayLabel: "Ethereum",
    type: AssetType.crypto,
    price: 3800,
    prevPrice: 3800,
    change24h: -1.2,
    isForexRate: false,
  },
  {
    name: "BNB",
    displayLabel: "Binance Coin",
    type: AssetType.crypto,
    price: 590,
    prevPrice: 590,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "SOL",
    displayLabel: "Solana",
    type: AssetType.crypto,
    price: 175,
    prevPrice: 175,
    change24h: 4.1,
    isForexRate: false,
  },
  {
    name: "XRP",
    displayLabel: "Ripple",
    type: AssetType.crypto,
    price: 0.62,
    prevPrice: 0.62,
    change24h: 5.8,
    isForexRate: false,
  },
  {
    name: "ADA",
    displayLabel: "Cardano",
    type: AssetType.crypto,
    price: 0.45,
    prevPrice: 0.45,
    change24h: -2.3,
    isForexRate: false,
  },
  {
    name: "DOGE",
    displayLabel: "Dogecoin",
    type: AssetType.crypto,
    price: 0.18,
    prevPrice: 0.18,
    change24h: 7.2,
    isForexRate: false,
  },
  {
    name: "DOT",
    displayLabel: "Polkadot",
    type: AssetType.crypto,
    price: 8.4,
    prevPrice: 8.4,
    change24h: -0.5,
    isForexRate: false,
  },
  {
    name: "MATIC",
    displayLabel: "Polygon",
    type: AssetType.crypto,
    price: 0.92,
    prevPrice: 0.92,
    change24h: 3.1,
    isForexRate: false,
  },
  {
    name: "SHIB",
    displayLabel: "Shiba Inu",
    type: AssetType.crypto,
    price: 0.000028,
    prevPrice: 0.000028,
    change24h: 12.4,
    isForexRate: false,
  },
  {
    name: "AVAX",
    displayLabel: "Avalanche",
    type: AssetType.crypto,
    price: 38,
    prevPrice: 38,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "LINK",
    displayLabel: "Chainlink",
    type: AssetType.crypto,
    price: 18.5,
    prevPrice: 18.5,
    change24h: -1.7,
    isForexRate: false,
  },
  {
    name: "UNI",
    displayLabel: "Uniswap",
    type: AssetType.crypto,
    price: 10.2,
    prevPrice: 10.2,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "LTC",
    displayLabel: "Litecoin",
    type: AssetType.crypto,
    price: 92,
    prevPrice: 92,
    change24h: -0.9,
    isForexRate: false,
  },
  {
    name: "BCH",
    displayLabel: "Bitcoin Cash",
    type: AssetType.crypto,
    price: 480,
    prevPrice: 480,
    change24h: 2.0,
    isForexRate: false,
  },
  {
    name: "ATOM",
    displayLabel: "Cosmos",
    type: AssetType.crypto,
    price: 10.8,
    prevPrice: 10.8,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "FIL",
    displayLabel: "Filecoin",
    type: AssetType.crypto,
    price: 5.9,
    prevPrice: 5.9,
    change24h: -3.2,
    isForexRate: false,
  },
  {
    name: "ALGO",
    displayLabel: "Algorand",
    type: AssetType.crypto,
    price: 0.22,
    prevPrice: 0.22,
    change24h: 0.3,
    isForexRate: false,
  },
  {
    name: "VET",
    displayLabel: "VeChain",
    type: AssetType.crypto,
    price: 0.038,
    prevPrice: 0.038,
    change24h: 4.5,
    isForexRate: false,
  },
  {
    name: "ICP",
    displayLabel: "Internet Computer",
    type: AssetType.crypto,
    price: 12.4,
    prevPrice: 12.4,
    change24h: 6.1,
    isForexRate: false,
  },
  {
    name: "XLM",
    displayLabel: "Stellar",
    type: AssetType.crypto,
    price: 0.14,
    prevPrice: 0.14,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "ETC",
    displayLabel: "Ethereum Classic",
    type: AssetType.crypto,
    price: 28,
    prevPrice: 28,
    change24h: -1.1,
    isForexRate: false,
  },
  {
    name: "APT",
    displayLabel: "Aptos",
    type: AssetType.crypto,
    price: 9.5,
    prevPrice: 9.5,
    change24h: 3.7,
    isForexRate: false,
  },
  {
    name: "OP",
    displayLabel: "Optimism",
    type: AssetType.crypto,
    price: 2.4,
    prevPrice: 2.4,
    change24h: -0.4,
    isForexRate: false,
  },
  {
    name: "ARB",
    displayLabel: "Arbitrum",
    type: AssetType.crypto,
    price: 1.05,
    prevPrice: 1.05,
    change24h: 1.6,
    isForexRate: false,
  },
  {
    name: "SUI",
    displayLabel: "Sui",
    type: AssetType.crypto,
    price: 1.38,
    prevPrice: 1.38,
    change24h: 8.2,
    isForexRate: false,
  },
  {
    name: "TRX",
    displayLabel: "TRON",
    type: AssetType.crypto,
    price: 0.12,
    prevPrice: 0.12,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "NEAR",
    displayLabel: "NEAR Protocol",
    type: AssetType.crypto,
    price: 7.2,
    prevPrice: 7.2,
    change24h: 2.2,
    isForexRate: false,
  },
  {
    name: "HBAR",
    displayLabel: "Hedera",
    type: AssetType.crypto,
    price: 0.11,
    prevPrice: 0.11,
    change24h: 5.0,
    isForexRate: false,
  },
  {
    name: "CRO",
    displayLabel: "Cronos",
    type: AssetType.crypto,
    price: 0.096,
    prevPrice: 0.096,
    change24h: -1.5,
    isForexRate: false,
  },
  {
    name: "QNT",
    displayLabel: "Quant",
    type: AssetType.crypto,
    price: 110,
    prevPrice: 110,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "AAVE",
    displayLabel: "Aave",
    type: AssetType.crypto,
    price: 105,
    prevPrice: 105,
    change24h: -2.8,
    isForexRate: false,
  },
  {
    name: "MKR",
    displayLabel: "Maker",
    type: AssetType.crypto,
    price: 2950,
    prevPrice: 2950,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "GRT",
    displayLabel: "The Graph",
    type: AssetType.crypto,
    price: 0.28,
    prevPrice: 0.28,
    change24h: 3.6,
    isForexRate: false,
  },
  {
    name: "FTM",
    displayLabel: "Fantom",
    type: AssetType.crypto,
    price: 0.82,
    prevPrice: 0.82,
    change24h: 6.3,
    isForexRate: false,
  },
  {
    name: "INJ",
    displayLabel: "Injective",
    type: AssetType.crypto,
    price: 32,
    prevPrice: 32,
    change24h: 4.8,
    isForexRate: false,
  },
  {
    name: "RUNE",
    displayLabel: "THORChain",
    type: AssetType.crypto,
    price: 5.6,
    prevPrice: 5.6,
    change24h: -0.6,
    isForexRate: false,
  },
  {
    name: "SEI",
    displayLabel: "Sei",
    type: AssetType.crypto,
    price: 0.62,
    prevPrice: 0.62,
    change24h: 9.1,
    isForexRate: false,
  },
  {
    name: "PEPE",
    displayLabel: "Pepe",
    type: AssetType.crypto,
    price: 0.0000138,
    prevPrice: 0.0000138,
    change24h: 15.2,
    isForexRate: false,
  },
  {
    name: "WIF",
    displayLabel: "dogwifhat",
    type: AssetType.crypto,
    price: 2.85,
    prevPrice: 2.85,
    change24h: 11.4,
    isForexRate: false,
  },
  {
    name: "BONK",
    displayLabel: "Bonk",
    type: AssetType.crypto,
    price: 0.0000295,
    prevPrice: 0.0000295,
    change24h: 8.7,
    isForexRate: false,
  },
  {
    name: "FLOKI",
    displayLabel: "Floki Inu",
    type: AssetType.crypto,
    price: 0.000185,
    prevPrice: 0.000185,
    change24h: 6.5,
    isForexRate: false,
  },
  {
    name: "1000SATS",
    displayLabel: "1000SATS",
    type: AssetType.crypto,
    price: 0.000478,
    prevPrice: 0.000478,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "ORDI",
    displayLabel: "Ordinals",
    type: AssetType.crypto,
    price: 52,
    prevPrice: 52,
    change24h: 7.3,
    isForexRate: false,
  },
  {
    name: "STX",
    displayLabel: "Stacks",
    type: AssetType.crypto,
    price: 2.8,
    prevPrice: 2.8,
    change24h: 3.9,
    isForexRate: false,
  },
  {
    name: "WLD",
    displayLabel: "Worldcoin",
    type: AssetType.crypto,
    price: 4.75,
    prevPrice: 4.75,
    change24h: -2.1,
    isForexRate: false,
  },
  {
    name: "JUP",
    displayLabel: "Jupiter",
    type: AssetType.crypto,
    price: 1.12,
    prevPrice: 1.12,
    change24h: 5.4,
    isForexRate: false,
  },
  {
    name: "PYTH",
    displayLabel: "Pyth Network",
    type: AssetType.crypto,
    price: 0.52,
    prevPrice: 0.52,
    change24h: 3.8,
    isForexRate: false,
  },
  {
    name: "TIA",
    displayLabel: "Celestia",
    type: AssetType.crypto,
    price: 10.5,
    prevPrice: 10.5,
    change24h: 6.2,
    isForexRate: false,
  },
  {
    name: "BLUR",
    displayLabel: "Blur",
    type: AssetType.crypto,
    price: 0.38,
    prevPrice: 0.38,
    change24h: -1.9,
    isForexRate: false,
  },
  {
    name: "CFX",
    displayLabel: "Conflux",
    type: AssetType.crypto,
    price: 0.24,
    prevPrice: 0.24,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "MANTA",
    displayLabel: "Manta Network",
    type: AssetType.crypto,
    price: 1.82,
    prevPrice: 1.82,
    change24h: 4.6,
    isForexRate: false,
  },
  {
    name: "ALT",
    displayLabel: "AltLayer",
    type: AssetType.crypto,
    price: 0.42,
    prevPrice: 0.42,
    change24h: 7.1,
    isForexRate: false,
  },
  {
    name: "PIXEL",
    displayLabel: "Pixels",
    type: AssetType.crypto,
    price: 0.38,
    prevPrice: 0.38,
    change24h: 12.5,
    isForexRate: false,
  },
  {
    name: "DYM",
    displayLabel: "Dymension",
    type: AssetType.crypto,
    price: 4.2,
    prevPrice: 4.2,
    change24h: -3.4,
    isForexRate: false,
  },
  {
    name: "MEME",
    displayLabel: "Memecoin",
    type: AssetType.crypto,
    price: 0.032,
    prevPrice: 0.032,
    change24h: 9.8,
    isForexRate: false,
  },
  {
    name: "ACE",
    displayLabel: "Fusionist",
    type: AssetType.crypto,
    price: 8.5,
    prevPrice: 8.5,
    change24h: 5.3,
    isForexRate: false,
  },
  {
    name: "BEAMX",
    displayLabel: "Beam",
    type: AssetType.crypto,
    price: 0.024,
    prevPrice: 0.024,
    change24h: 3.7,
    isForexRate: false,
  },
  {
    name: "CYBER",
    displayLabel: "CyberConnect",
    type: AssetType.crypto,
    price: 6.4,
    prevPrice: 6.4,
    change24h: 2.9,
    isForexRate: false,
  },
  {
    name: "USUAL",
    displayLabel: "Usual",
    type: AssetType.crypto,
    price: 0.95,
    prevPrice: 0.95,
    change24h: 14.2,
    isForexRate: false,
  },
  {
    name: "EIGEN",
    displayLabel: "EigenLayer",
    type: AssetType.crypto,
    price: 3.8,
    prevPrice: 3.8,
    change24h: 6.7,
    isForexRate: false,
  },
  {
    name: "HMSTR",
    displayLabel: "Hamster Kombat",
    type: AssetType.crypto,
    price: 0.0058,
    prevPrice: 0.0058,
    change24h: -5.2,
    isForexRate: false,
  },
  {
    name: "CATI",
    displayLabel: "Catizen",
    type: AssetType.crypto,
    price: 0.68,
    prevPrice: 0.68,
    change24h: 8.1,
    isForexRate: false,
  },
  {
    name: "NOT",
    displayLabel: "Notcoin",
    type: AssetType.crypto,
    price: 0.0185,
    prevPrice: 0.0185,
    change24h: 4.3,
    isForexRate: false,
  },
  {
    name: "TAO",
    displayLabel: "Bittensor",
    type: AssetType.crypto,
    price: 450,
    prevPrice: 450,
    change24h: 7.8,
    isForexRate: false,
  },
  {
    name: "STRK",
    displayLabel: "Starknet",
    type: AssetType.crypto,
    price: 0.92,
    prevPrice: 0.92,
    change24h: -1.6,
    isForexRate: false,
  },
  {
    name: "W",
    displayLabel: "Wormhole",
    type: AssetType.crypto,
    price: 0.45,
    prevPrice: 0.45,
    change24h: 5.9,
    isForexRate: false,
  },
  {
    name: "ENA",
    displayLabel: "Ethena",
    type: AssetType.crypto,
    price: 0.72,
    prevPrice: 0.72,
    change24h: 9.4,
    isForexRate: false,
  },
  {
    name: "IO",
    displayLabel: "io.net",
    type: AssetType.crypto,
    price: 3.6,
    prevPrice: 3.6,
    change24h: 11.2,
    isForexRate: false,
  },
  {
    name: "ZK",
    displayLabel: "ZKsync",
    type: AssetType.crypto,
    price: 0.18,
    prevPrice: 0.18,
    change24h: 3.5,
    isForexRate: false,
  },
  {
    name: "LISTA",
    displayLabel: "Lista DAO",
    type: AssetType.crypto,
    price: 0.42,
    prevPrice: 0.42,
    change24h: 6.8,
    isForexRate: false,
  },
  {
    name: "DOGS",
    displayLabel: "Dogs",
    type: AssetType.crypto,
    price: 0.00082,
    prevPrice: 0.00082,
    change24h: 18.5,
    isForexRate: false,
  },
  {
    name: "NEIRO",
    displayLabel: "First Neiro",
    type: AssetType.crypto,
    price: 0.00145,
    prevPrice: 0.00145,
    change24h: 22.3,
    isForexRate: false,
  },
  {
    name: "BABYDOGE",
    displayLabel: "Baby Doge Coin",
    type: AssetType.crypto,
    price: 0.0000000025,
    prevPrice: 0.0000000025,
    change24h: 9.1,
    isForexRate: false,
  },
  {
    name: "RENDER",
    displayLabel: "Render",
    type: AssetType.crypto,
    price: 8.2,
    prevPrice: 8.2,
    change24h: 4.7,
    isForexRate: false,
  },
  {
    name: "FET",
    displayLabel: "Fetch.ai",
    type: AssetType.crypto,
    price: 1.85,
    prevPrice: 1.85,
    change24h: 6.3,
    isForexRate: false,
  },
  {
    name: "AGIX",
    displayLabel: "SingularityNET",
    type: AssetType.crypto,
    price: 0.92,
    prevPrice: 0.92,
    change24h: 5.4,
    isForexRate: false,
  },
  {
    name: "OCEAN",
    displayLabel: "Ocean Protocol",
    type: AssetType.crypto,
    price: 0.98,
    prevPrice: 0.98,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "RNDR",
    displayLabel: "Render Token",
    type: AssetType.crypto,
    price: 8.4,
    prevPrice: 8.4,
    change24h: 4.9,
    isForexRate: false,
  },
  {
    name: "PENDLE",
    displayLabel: "Pendle",
    type: AssetType.crypto,
    price: 5.8,
    prevPrice: 5.8,
    change24h: 7.6,
    isForexRate: false,
  },
  {
    name: "JTO",
    displayLabel: "Jito",
    type: AssetType.crypto,
    price: 3.9,
    prevPrice: 3.9,
    change24h: 5.1,
    isForexRate: false,
  },
  {
    name: "BONK",
    displayLabel: "Bonk",
    type: AssetType.crypto,
    price: 0.0000295,
    prevPrice: 0.0000295,
    change24h: 8.7,
    isForexRate: false,
  },
  {
    name: "PYUSD",
    displayLabel: "PayPal USD",
    type: AssetType.crypto,
    price: 1.0,
    prevPrice: 1.0,
    change24h: 0.01,
    isForexRate: false,
  },
  {
    name: "USDC",
    displayLabel: "USD Coin",
    type: AssetType.crypto,
    price: 1.0,
    prevPrice: 1.0,
    change24h: 0.0,
    isForexRate: false,
  },
  {
    name: "USDT",
    displayLabel: "Tether",
    type: AssetType.crypto,
    price: 1.0,
    prevPrice: 1.0,
    change24h: 0.0,
    isForexRate: false,
  },
  {
    name: "BUSD",
    displayLabel: "Binance USD",
    type: AssetType.crypto,
    price: 1.0,
    prevPrice: 1.0,
    change24h: 0.0,
    isForexRate: false,
  },
  {
    name: "DAI",
    displayLabel: "Dai",
    type: AssetType.crypto,
    price: 1.0,
    prevPrice: 1.0,
    change24h: 0.0,
    isForexRate: false,
  },
  {
    name: "XMR",
    displayLabel: "Monero",
    type: AssetType.crypto,
    price: 162,
    prevPrice: 162,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "DASH",
    displayLabel: "Dash",
    type: AssetType.crypto,
    price: 35,
    prevPrice: 35,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "ZEC",
    displayLabel: "Zcash",
    type: AssetType.crypto,
    price: 22,
    prevPrice: 22,
    change24h: -1.2,
    isForexRate: false,
  },
  {
    name: "EOS",
    displayLabel: "EOS",
    type: AssetType.crypto,
    price: 0.82,
    prevPrice: 0.82,
    change24h: -2.1,
    isForexRate: false,
  },
  {
    name: "XTZ",
    displayLabel: "Tezos",
    type: AssetType.crypto,
    price: 1.05,
    prevPrice: 1.05,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "WAVES",
    displayLabel: "Waves",
    type: AssetType.crypto,
    price: 2.5,
    prevPrice: 2.5,
    change24h: 3.4,
    isForexRate: false,
  },
  {
    name: "ZIL",
    displayLabel: "Zilliqa",
    type: AssetType.crypto,
    price: 0.022,
    prevPrice: 0.022,
    change24h: 5.6,
    isForexRate: false,
  },
  {
    name: "ICX",
    displayLabel: "ICON",
    type: AssetType.crypto,
    price: 0.28,
    prevPrice: 0.28,
    change24h: 2.3,
    isForexRate: false,
  },
  {
    name: "ONT",
    displayLabel: "Ontology",
    type: AssetType.crypto,
    price: 0.18,
    prevPrice: 0.18,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "BAT",
    displayLabel: "Basic Attention Token",
    type: AssetType.crypto,
    price: 0.25,
    prevPrice: 0.25,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "ENJ",
    displayLabel: "Enjin Coin",
    type: AssetType.crypto,
    price: 0.26,
    prevPrice: 0.26,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "CHZ",
    displayLabel: "Chiliz",
    type: AssetType.crypto,
    price: 0.088,
    prevPrice: 0.088,
    change24h: 4.7,
    isForexRate: false,
  },
  {
    name: "SAND",
    displayLabel: "The Sandbox",
    type: AssetType.crypto,
    price: 0.42,
    prevPrice: 0.42,
    change24h: 3.8,
    isForexRate: false,
  },
  {
    name: "MANA",
    displayLabel: "Decentraland",
    type: AssetType.crypto,
    price: 0.38,
    prevPrice: 0.38,
    change24h: 2.9,
    isForexRate: false,
  },
  {
    name: "AXS",
    displayLabel: "Axie Infinity",
    type: AssetType.crypto,
    price: 6.8,
    prevPrice: 6.8,
    change24h: 5.2,
    isForexRate: false,
  },
  {
    name: "GALA",
    displayLabel: "Gala",
    type: AssetType.crypto,
    price: 0.038,
    prevPrice: 0.038,
    change24h: 7.3,
    isForexRate: false,
  },
  {
    name: "IMX",
    displayLabel: "Immutable",
    type: AssetType.crypto,
    price: 1.75,
    prevPrice: 1.75,
    change24h: 4.1,
    isForexRate: false,
  },
  {
    name: "FLOW",
    displayLabel: "Flow",
    type: AssetType.crypto,
    price: 0.72,
    prevPrice: 0.72,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "ROSE",
    displayLabel: "Oasis Network",
    type: AssetType.crypto,
    price: 0.092,
    prevPrice: 0.092,
    change24h: 3.5,
    isForexRate: false,
  },
  {
    name: "ONE",
    displayLabel: "Harmony",
    type: AssetType.crypto,
    price: 0.018,
    prevPrice: 0.018,
    change24h: 2.7,
    isForexRate: false,
  },
  {
    name: "IOTA",
    displayLabel: "IOTA",
    type: AssetType.crypto,
    price: 0.22,
    prevPrice: 0.22,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "HOT",
    displayLabel: "Holo",
    type: AssetType.crypto,
    price: 0.0022,
    prevPrice: 0.0022,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "CELR",
    displayLabel: "Celer Network",
    type: AssetType.crypto,
    price: 0.018,
    prevPrice: 0.018,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "BAND",
    displayLabel: "Band Protocol",
    type: AssetType.crypto,
    price: 1.45,
    prevPrice: 1.45,
    change24h: 3.1,
    isForexRate: false,
  },
  {
    name: "CKB",
    displayLabel: "Nervos Network",
    type: AssetType.crypto,
    price: 0.012,
    prevPrice: 0.012,
    change24h: 5.4,
    isForexRate: false,
  },
  {
    name: "ANKR",
    displayLabel: "Ankr",
    type: AssetType.crypto,
    price: 0.048,
    prevPrice: 0.048,
    change24h: 3.6,
    isForexRate: false,
  },
  {
    name: "LUNC",
    displayLabel: "Terra Classic",
    type: AssetType.crypto,
    price: 0.000095,
    prevPrice: 0.000095,
    change24h: 6.8,
    isForexRate: false,
  },
  {
    name: "LUNA",
    displayLabel: "Terra",
    type: AssetType.crypto,
    price: 0.58,
    prevPrice: 0.58,
    change24h: 4.3,
    isForexRate: false,
  },
  {
    name: "KAVA",
    displayLabel: "Kava",
    type: AssetType.crypto,
    price: 0.72,
    prevPrice: 0.72,
    change24h: 2.5,
    isForexRate: false,
  },
  {
    name: "CELO",
    displayLabel: "Celo",
    type: AssetType.crypto,
    price: 0.88,
    prevPrice: 0.88,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "IOST",
    displayLabel: "IOST",
    type: AssetType.crypto,
    price: 0.012,
    prevPrice: 0.012,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "WAN",
    displayLabel: "Wanchain",
    type: AssetType.crypto,
    price: 0.28,
    prevPrice: 0.28,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "SC",
    displayLabel: "Siacoin",
    type: AssetType.crypto,
    price: 0.0065,
    prevPrice: 0.0065,
    change24h: 3.7,
    isForexRate: false,
  },
  {
    name: "THETA",
    displayLabel: "Theta Network",
    type: AssetType.crypto,
    price: 1.48,
    prevPrice: 1.48,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "TFUEL",
    displayLabel: "Theta Fuel",
    type: AssetType.crypto,
    price: 0.095,
    prevPrice: 0.095,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "AUDIO",
    displayLabel: "Audius",
    type: AssetType.crypto,
    price: 0.18,
    prevPrice: 0.18,
    change24h: 4.5,
    isForexRate: false,
  },
  {
    name: "DYDX",
    displayLabel: "dYdX",
    type: AssetType.crypto,
    price: 1.85,
    prevPrice: 1.85,
    change24h: 5.8,
    isForexRate: false,
  },
  {
    name: "SNX",
    displayLabel: "Synthetix",
    type: AssetType.crypto,
    price: 2.8,
    prevPrice: 2.8,
    change24h: 3.1,
    isForexRate: false,
  },
  {
    name: "CRV",
    displayLabel: "Curve DAO",
    type: AssetType.crypto,
    price: 0.42,
    prevPrice: 0.42,
    change24h: 2.7,
    isForexRate: false,
  },
  {
    name: "COMP",
    displayLabel: "Compound",
    type: AssetType.crypto,
    price: 55,
    prevPrice: 55,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "SUSHI",
    displayLabel: "SushiSwap",
    type: AssetType.crypto,
    price: 1.08,
    prevPrice: 1.08,
    change24h: 3.4,
    isForexRate: false,
  },
  {
    name: "1INCH",
    displayLabel: "1inch Network",
    type: AssetType.crypto,
    price: 0.42,
    prevPrice: 0.42,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "YFI",
    displayLabel: "yearn.finance",
    type: AssetType.crypto,
    price: 8200,
    prevPrice: 8200,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "BAL",
    displayLabel: "Balancer",
    type: AssetType.crypto,
    price: 3.2,
    prevPrice: 3.2,
    change24h: 2.3,
    isForexRate: false,
  },
  {
    name: "LDO",
    displayLabel: "Lido DAO",
    type: AssetType.crypto,
    price: 1.95,
    prevPrice: 1.95,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "RPL",
    displayLabel: "Rocket Pool",
    type: AssetType.crypto,
    price: 18,
    prevPrice: 18,
    change24h: 3.6,
    isForexRate: false,
  },
  {
    name: "SSV",
    displayLabel: "SSV Network",
    type: AssetType.crypto,
    price: 28,
    prevPrice: 28,
    change24h: 5.1,
    isForexRate: false,
  },
  {
    name: "ETHFI",
    displayLabel: "ether.fi",
    type: AssetType.crypto,
    price: 2.8,
    prevPrice: 2.8,
    change24h: 7.4,
    isForexRate: false,
  },
  {
    name: "REZ",
    displayLabel: "Renzo",
    type: AssetType.crypto,
    price: 0.085,
    prevPrice: 0.085,
    change24h: 9.2,
    isForexRate: false,
  },
  {
    name: "PUFFER",
    displayLabel: "Puffer Finance",
    type: AssetType.crypto,
    price: 0.32,
    prevPrice: 0.32,
    change24h: 6.8,
    isForexRate: false,
  },
  {
    name: "OMNI",
    displayLabel: "Omni Network",
    type: AssetType.crypto,
    price: 12.5,
    prevPrice: 12.5,
    change24h: 8.3,
    isForexRate: false,
  },
  {
    name: "SAGA",
    displayLabel: "Saga",
    type: AssetType.crypto,
    price: 2.45,
    prevPrice: 2.45,
    change24h: 5.7,
    isForexRate: false,
  },
  {
    name: "BB",
    displayLabel: "BounceBit",
    type: AssetType.crypto,
    price: 0.68,
    prevPrice: 0.68,
    change24h: 11.4,
    isForexRate: false,
  },
  {
    name: "AEVO",
    displayLabel: "Aevo",
    type: AssetType.crypto,
    price: 0.82,
    prevPrice: 0.82,
    change24h: 4.9,
    isForexRate: false,
  },
  {
    name: "PORTAL",
    displayLabel: "Portal",
    type: AssetType.crypto,
    price: 0.92,
    prevPrice: 0.92,
    change24h: 6.2,
    isForexRate: false,
  },
  {
    name: "BOME",
    displayLabel: "Book of Meme",
    type: AssetType.crypto,
    price: 0.0085,
    prevPrice: 0.0085,
    change24h: 13.5,
    isForexRate: false,
  },
  {
    name: "SLERF",
    displayLabel: "Slerf",
    type: AssetType.crypto,
    price: 0.062,
    prevPrice: 0.062,
    change24h: 9.7,
    isForexRate: false,
  },
  {
    name: "MEW",
    displayLabel: "cat in a dogs world",
    type: AssetType.crypto,
    price: 0.0065,
    prevPrice: 0.0065,
    change24h: 16.3,
    isForexRate: false,
  },
  {
    name: "BRETT",
    displayLabel: "Brett",
    type: AssetType.crypto,
    price: 0.082,
    prevPrice: 0.082,
    change24h: 14.8,
    isForexRate: false,
  },
  {
    name: "POPCAT",
    displayLabel: "Popcat",
    type: AssetType.crypto,
    price: 0.48,
    prevPrice: 0.48,
    change24h: 18.2,
    isForexRate: false,
  },
  {
    name: "MOG",
    displayLabel: "Mog Coin",
    type: AssetType.crypto,
    price: 0.0000018,
    prevPrice: 0.0000018,
    change24h: 12.7,
    isForexRate: false,
  },
  {
    name: "ZRO",
    displayLabel: "LayerZero",
    type: AssetType.crypto,
    price: 4.8,
    prevPrice: 4.8,
    change24h: 7.1,
    isForexRate: false,
  },
  {
    name: "TAIKO",
    displayLabel: "Taiko",
    type: AssetType.crypto,
    price: 1.95,
    prevPrice: 1.95,
    change24h: 5.4,
    isForexRate: false,
  },
  {
    name: "BLAST",
    displayLabel: "Blast",
    type: AssetType.crypto,
    price: 0.018,
    prevPrice: 0.018,
    change24h: 8.9,
    isForexRate: false,
  },
  {
    name: "MERL",
    displayLabel: "Merlin Chain",
    type: AssetType.crypto,
    price: 0.52,
    prevPrice: 0.52,
    change24h: 6.3,
    isForexRate: false,
  },
  {
    name: "VANRY",
    displayLabel: "Vanar Chain",
    type: AssetType.crypto,
    price: 0.082,
    prevPrice: 0.082,
    change24h: 4.8,
    isForexRate: false,
  },
  {
    name: "XAI",
    displayLabel: "Xai",
    type: AssetType.crypto,
    price: 0.32,
    prevPrice: 0.32,
    change24h: 7.6,
    isForexRate: false,
  },
  {
    name: "BIGTIME",
    displayLabel: "Big Time",
    type: AssetType.crypto,
    price: 0.18,
    prevPrice: 0.18,
    change24h: 5.9,
    isForexRate: false,
  },
  {
    name: "AGI",
    displayLabel: "Delysium",
    type: AssetType.crypto,
    price: 0.048,
    prevPrice: 0.048,
    change24h: 3.4,
    isForexRate: false,
  },
  {
    name: "HIGH",
    displayLabel: "Highstreet",
    type: AssetType.crypto,
    price: 2.85,
    prevPrice: 2.85,
    change24h: 4.7,
    isForexRate: false,
  },
  {
    name: "LAZIO",
    displayLabel: "Lazio Fan Token",
    type: AssetType.crypto,
    price: 1.68,
    prevPrice: 1.68,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "BAR",
    displayLabel: "FC Barcelona Fan",
    type: AssetType.crypto,
    price: 2.42,
    prevPrice: 2.42,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "PSG",
    displayLabel: "PSG Fan Token",
    type: AssetType.crypto,
    price: 3.85,
    prevPrice: 3.85,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "SANTOS",
    displayLabel: "Santos FC Fan",
    type: AssetType.crypto,
    price: 1.25,
    prevPrice: 1.25,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "ATM",
    displayLabel: "Atletico Fan Token",
    type: AssetType.crypto,
    price: 1.92,
    prevPrice: 1.92,
    change24h: 1.6,
    isForexRate: false,
  },
  {
    name: "CITY",
    displayLabel: "Manchester City Fan",
    type: AssetType.crypto,
    price: 2.15,
    prevPrice: 2.15,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "ACM",
    displayLabel: "AC Milan Fan Token",
    type: AssetType.crypto,
    price: 2.68,
    prevPrice: 2.68,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "JUV",
    displayLabel: "Juventus Fan Token",
    type: AssetType.crypto,
    price: 2.95,
    prevPrice: 2.95,
    change24h: 2.3,
    isForexRate: false,
  },
  {
    name: "ALPINE",
    displayLabel: "Alpine F1 Fan Token",
    type: AssetType.crypto,
    price: 1.48,
    prevPrice: 1.48,
    change24h: 3.5,
    isForexRate: false,
  },

  // ── FOREX – All major, minor & exotic pairs ────────────────────────────────
  {
    name: "EUR/USD",
    displayLabel: "Euro / US Dollar",
    type: AssetType.forex,
    price: 1.085,
    prevPrice: 1.085,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "GBP/USD",
    displayLabel: "British Pound / USD",
    type: AssetType.forex,
    price: 1.265,
    prevPrice: 1.265,
    change24h: -0.5,
    isForexRate: true,
  },
  {
    name: "USD/INR",
    displayLabel: "US Dollar / Rupee",
    type: AssetType.forex,
    price: 83.4,
    prevPrice: 83.4,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/JPY",
    displayLabel: "US Dollar / Yen",
    type: AssetType.forex,
    price: 151.6,
    prevPrice: 151.6,
    change24h: -0.2,
    isForexRate: true,
  },
  {
    name: "USD/AED",
    displayLabel: "US Dollar / Dirham",
    type: AssetType.forex,
    price: 3.673,
    prevPrice: 3.673,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "AUD/USD",
    displayLabel: "Australian Dollar / USD",
    type: AssetType.forex,
    price: 0.653,
    prevPrice: 0.653,
    change24h: 0.4,
    isForexRate: true,
  },
  {
    name: "USD/CHF",
    displayLabel: "US Dollar / Swiss Franc",
    type: AssetType.forex,
    price: 0.898,
    prevPrice: 0.898,
    change24h: -0.1,
    isForexRate: true,
  },
  {
    name: "USD/CAD",
    displayLabel: "US Dollar / Canadian $",
    type: AssetType.forex,
    price: 1.364,
    prevPrice: 1.364,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "NZD/USD",
    displayLabel: "NZ Dollar / USD",
    type: AssetType.forex,
    price: 0.609,
    prevPrice: 0.609,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "EUR/GBP",
    displayLabel: "Euro / British Pound",
    type: AssetType.forex,
    price: 0.857,
    prevPrice: 0.857,
    change24h: -0.1,
    isForexRate: true,
  },
  {
    name: "EUR/JPY",
    displayLabel: "Euro / Yen",
    type: AssetType.forex,
    price: 164.4,
    prevPrice: 164.4,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "GBP/JPY",
    displayLabel: "British Pound / Yen",
    type: AssetType.forex,
    price: 191.7,
    prevPrice: 191.7,
    change24h: -0.3,
    isForexRate: true,
  },
  {
    name: "EUR/CHF",
    displayLabel: "Euro / Swiss Franc",
    type: AssetType.forex,
    price: 0.974,
    prevPrice: 0.974,
    change24h: -0.2,
    isForexRate: true,
  },
  {
    name: "USD/SGD",
    displayLabel: "US Dollar / SGD",
    type: AssetType.forex,
    price: 1.346,
    prevPrice: 1.346,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/HKD",
    displayLabel: "US Dollar / HKD",
    type: AssetType.forex,
    price: 7.827,
    prevPrice: 7.827,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/CNY",
    displayLabel: "US Dollar / Yuan",
    type: AssetType.forex,
    price: 7.238,
    prevPrice: 7.238,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/KRW",
    displayLabel: "US Dollar / Korean Won",
    type: AssetType.forex,
    price: 1325,
    prevPrice: 1325,
    change24h: -0.2,
    isForexRate: true,
  },
  {
    name: "USD/MXN",
    displayLabel: "US Dollar / Mexican Peso",
    type: AssetType.forex,
    price: 16.9,
    prevPrice: 16.9,
    change24h: 0.5,
    isForexRate: true,
  },
  {
    name: "USD/BRL",
    displayLabel: "US Dollar / Brazilian Real",
    type: AssetType.forex,
    price: 4.97,
    prevPrice: 4.97,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "USD/ZAR",
    displayLabel: "US Dollar / S. African Rand",
    type: AssetType.forex,
    price: 18.6,
    prevPrice: 18.6,
    change24h: -0.4,
    isForexRate: true,
  },
  {
    name: "EUR/INR",
    displayLabel: "Euro / Indian Rupee",
    type: AssetType.forex,
    price: 90.4,
    prevPrice: 90.4,
    change24h: 0.4,
    isForexRate: true,
  },
  {
    name: "GBP/INR",
    displayLabel: "British Pound / Rupee",
    type: AssetType.forex,
    price: 105.5,
    prevPrice: 105.5,
    change24h: -0.3,
    isForexRate: true,
  },
  {
    name: "AED/INR",
    displayLabel: "Dirham / Indian Rupee",
    type: AssetType.forex,
    price: 22.7,
    prevPrice: 22.7,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "EUR/AED",
    displayLabel: "Euro / Dirham",
    type: AssetType.forex,
    price: 3.985,
    prevPrice: 3.985,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "XAU/USD",
    displayLabel: "Gold / USD (Spot)",
    type: AssetType.forex,
    price: 2320,
    prevPrice: 2320,
    change24h: 0.6,
    isForexRate: true,
  },
  {
    name: "XAG/USD",
    displayLabel: "Silver / USD (Spot)",
    type: AssetType.forex,
    price: 28.5,
    prevPrice: 28.5,
    change24h: 0.8,
    isForexRate: true,
  },
  {
    name: "XPT/USD",
    displayLabel: "Platinum / USD",
    type: AssetType.forex,
    price: 985,
    prevPrice: 985,
    change24h: 0.4,
    isForexRate: true,
  },
  {
    name: "XPD/USD",
    displayLabel: "Palladium / USD",
    type: AssetType.forex,
    price: 1045,
    prevPrice: 1045,
    change24h: -0.6,
    isForexRate: true,
  },
  {
    name: "USD/TRY",
    displayLabel: "US Dollar / Turkish Lira",
    type: AssetType.forex,
    price: 32.4,
    prevPrice: 32.4,
    change24h: 0.8,
    isForexRate: true,
  },
  {
    name: "USD/SEK",
    displayLabel: "US Dollar / Swedish Krona",
    type: AssetType.forex,
    price: 10.52,
    prevPrice: 10.52,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "USD/NOK",
    displayLabel: "US Dollar / Norwegian Krone",
    type: AssetType.forex,
    price: 10.68,
    prevPrice: 10.68,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "USD/DKK",
    displayLabel: "US Dollar / Danish Krone",
    type: AssetType.forex,
    price: 6.88,
    prevPrice: 6.88,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/PLN",
    displayLabel: "US Dollar / Polish Zloty",
    type: AssetType.forex,
    price: 3.98,
    prevPrice: 3.98,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "USD/CZK",
    displayLabel: "US Dollar / Czech Koruna",
    type: AssetType.forex,
    price: 23.2,
    prevPrice: 23.2,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/HUF",
    displayLabel: "US Dollar / Hungarian Forint",
    type: AssetType.forex,
    price: 355,
    prevPrice: 355,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "USD/RUB",
    displayLabel: "US Dollar / Russian Ruble",
    type: AssetType.forex,
    price: 91.5,
    prevPrice: 91.5,
    change24h: 0.5,
    isForexRate: true,
  },
  {
    name: "USD/THB",
    displayLabel: "US Dollar / Thai Baht",
    type: AssetType.forex,
    price: 35.8,
    prevPrice: 35.8,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/MYR",
    displayLabel: "US Dollar / Malaysian Ringgit",
    type: AssetType.forex,
    price: 4.72,
    prevPrice: 4.72,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "USD/IDR",
    displayLabel: "US Dollar / Indonesian Rupiah",
    type: AssetType.forex,
    price: 15680,
    prevPrice: 15680,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "USD/PHP",
    displayLabel: "US Dollar / Philippine Peso",
    type: AssetType.forex,
    price: 56.8,
    prevPrice: 56.8,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/VND",
    displayLabel: "US Dollar / Vietnamese Dong",
    type: AssetType.forex,
    price: 24850,
    prevPrice: 24850,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/EGP",
    displayLabel: "US Dollar / Egyptian Pound",
    type: AssetType.forex,
    price: 30.9,
    prevPrice: 30.9,
    change24h: 0.4,
    isForexRate: true,
  },
  {
    name: "USD/NGN",
    displayLabel: "US Dollar / Nigerian Naira",
    type: AssetType.forex,
    price: 1520,
    prevPrice: 1520,
    change24h: 0.6,
    isForexRate: true,
  },
  {
    name: "USD/PKR",
    displayLabel: "US Dollar / Pakistani Rupee",
    type: AssetType.forex,
    price: 278,
    prevPrice: 278,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "USD/BDT",
    displayLabel: "US Dollar / Bangladeshi Taka",
    type: AssetType.forex,
    price: 110,
    prevPrice: 110,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "USD/SAR",
    displayLabel: "US Dollar / Saudi Riyal",
    type: AssetType.forex,
    price: 3.75,
    prevPrice: 3.75,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/QAR",
    displayLabel: "US Dollar / Qatari Riyal",
    type: AssetType.forex,
    price: 3.64,
    prevPrice: 3.64,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/KWD",
    displayLabel: "US Dollar / Kuwaiti Dinar",
    type: AssetType.forex,
    price: 0.308,
    prevPrice: 0.308,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/OMR",
    displayLabel: "US Dollar / Omani Rial",
    type: AssetType.forex,
    price: 0.385,
    prevPrice: 0.385,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/BHD",
    displayLabel: "US Dollar / Bahraini Dinar",
    type: AssetType.forex,
    price: 0.377,
    prevPrice: 0.377,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "USD/JOD",
    displayLabel: "US Dollar / Jordanian Dinar",
    type: AssetType.forex,
    price: 0.709,
    prevPrice: 0.709,
    change24h: 0.0,
    isForexRate: true,
  },
  {
    name: "EUR/CAD",
    displayLabel: "Euro / Canadian Dollar",
    type: AssetType.forex,
    price: 1.48,
    prevPrice: 1.48,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "EUR/AUD",
    displayLabel: "Euro / Australian Dollar",
    type: AssetType.forex,
    price: 1.66,
    prevPrice: 1.66,
    change24h: -0.1,
    isForexRate: true,
  },
  {
    name: "EUR/NZD",
    displayLabel: "Euro / NZ Dollar",
    type: AssetType.forex,
    price: 1.78,
    prevPrice: 1.78,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "GBP/AUD",
    displayLabel: "British Pound / AUD",
    type: AssetType.forex,
    price: 1.94,
    prevPrice: 1.94,
    change24h: -0.2,
    isForexRate: true,
  },
  {
    name: "GBP/CAD",
    displayLabel: "British Pound / CAD",
    type: AssetType.forex,
    price: 1.72,
    prevPrice: 1.72,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "GBP/NZD",
    displayLabel: "British Pound / NZD",
    type: AssetType.forex,
    price: 2.08,
    prevPrice: 2.08,
    change24h: -0.3,
    isForexRate: true,
  },
  {
    name: "AUD/JPY",
    displayLabel: "Australian Dollar / Yen",
    type: AssetType.forex,
    price: 99.1,
    prevPrice: 99.1,
    change24h: 0.3,
    isForexRate: true,
  },
  {
    name: "AUD/NZD",
    displayLabel: "Australian Dollar / NZD",
    type: AssetType.forex,
    price: 1.072,
    prevPrice: 1.072,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "AUD/CAD",
    displayLabel: "Australian Dollar / CAD",
    type: AssetType.forex,
    price: 0.891,
    prevPrice: 0.891,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "CAD/JPY",
    displayLabel: "Canadian Dollar / Yen",
    type: AssetType.forex,
    price: 111.2,
    prevPrice: 111.2,
    change24h: -0.1,
    isForexRate: true,
  },
  {
    name: "CHF/JPY",
    displayLabel: "Swiss Franc / Yen",
    type: AssetType.forex,
    price: 168.7,
    prevPrice: 168.7,
    change24h: 0.2,
    isForexRate: true,
  },
  {
    name: "NZD/JPY",
    displayLabel: "NZ Dollar / Yen",
    type: AssetType.forex,
    price: 92.3,
    prevPrice: 92.3,
    change24h: 0.1,
    isForexRate: true,
  },
  {
    name: "WTI/USD",
    displayLabel: "Crude Oil WTI / USD",
    type: AssetType.forex,
    price: 82.5,
    prevPrice: 82.5,
    change24h: 1.2,
    isForexRate: true,
  },
  {
    name: "BRENT/USD",
    displayLabel: "Brent Crude / USD",
    type: AssetType.forex,
    price: 86.8,
    prevPrice: 86.8,
    change24h: 1.0,
    isForexRate: true,
  },
  {
    name: "NG/USD",
    displayLabel: "Natural Gas / USD",
    type: AssetType.forex,
    price: 2.85,
    prevPrice: 2.85,
    change24h: -0.8,
    isForexRate: true,
  },
  {
    name: "COPPER/USD",
    displayLabel: "Copper / USD",
    type: AssetType.forex,
    price: 4.28,
    prevPrice: 4.28,
    change24h: 0.7,
    isForexRate: true,
  },

  // ── STOCKS – Groww listed (India NSE/BSE + US) ────────────────────────────
  // Indian Indices
  {
    name: "NIFTY50",
    displayLabel: "NIFTY 50",
    type: AssetType.stock,
    price: 22500,
    prevPrice: 22500,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "SENSEX",
    displayLabel: "BSE SENSEX",
    type: AssetType.stock,
    price: 74200,
    prevPrice: 74200,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "BANKNIFTY",
    displayLabel: "Bank Nifty",
    type: AssetType.stock,
    price: 48500,
    prevPrice: 48500,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "NIFTYIT",
    displayLabel: "Nifty IT",
    type: AssetType.stock,
    price: 36200,
    prevPrice: 36200,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "NIFTYMIDCAP",
    displayLabel: "Nifty Midcap 100",
    type: AssetType.stock,
    price: 48800,
    prevPrice: 48800,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "NIFTYSMALLCAP",
    displayLabel: "Nifty Smallcap 100",
    type: AssetType.stock,
    price: 14200,
    prevPrice: 14200,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "NIFTYNEXT50",
    displayLabel: "Nifty Next 50",
    type: AssetType.stock,
    price: 67800,
    prevPrice: 67800,
    change24h: 1.2,
    isForexRate: false,
  },
  // Large Cap Indian Stocks
  {
    name: "RELIANCE",
    displayLabel: "Reliance Industries",
    type: AssetType.stock,
    price: 2920,
    prevPrice: 2920,
    change24h: -0.8,
    isForexRate: false,
  },
  {
    name: "TCS",
    displayLabel: "TCS",
    type: AssetType.stock,
    price: 3850,
    prevPrice: 3850,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "HDFCBANK",
    displayLabel: "HDFC Bank",
    type: AssetType.stock,
    price: 1640,
    prevPrice: 1640,
    change24h: 1.2,
    isForexRate: false,
  },
  {
    name: "INFY",
    displayLabel: "Infosys",
    type: AssetType.stock,
    price: 1780,
    prevPrice: 1780,
    change24h: -0.3,
    isForexRate: false,
  },
  {
    name: "HINDUNILVR",
    displayLabel: "Hindustan Unilever",
    type: AssetType.stock,
    price: 2450,
    prevPrice: 2450,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "ICICIBANK",
    displayLabel: "ICICI Bank",
    type: AssetType.stock,
    price: 1080,
    prevPrice: 1080,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "SBI",
    displayLabel: "State Bank of India",
    type: AssetType.stock,
    price: 780,
    prevPrice: 780,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "BHARTIARTL",
    displayLabel: "Bharti Airtel",
    type: AssetType.stock,
    price: 1380,
    prevPrice: 1380,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "KOTAKBANK",
    displayLabel: "Kotak Mahindra Bank",
    type: AssetType.stock,
    price: 1780,
    prevPrice: 1780,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "WIPRO",
    displayLabel: "Wipro",
    type: AssetType.stock,
    price: 460,
    prevPrice: 460,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "HCLTECH",
    displayLabel: "HCL Technologies",
    type: AssetType.stock,
    price: 1520,
    prevPrice: 1520,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "ASIANPAINT",
    displayLabel: "Asian Paints",
    type: AssetType.stock,
    price: 2820,
    prevPrice: 2820,
    change24h: -0.5,
    isForexRate: false,
  },
  {
    name: "MARUTI",
    displayLabel: "Maruti Suzuki",
    type: AssetType.stock,
    price: 12400,
    prevPrice: 12400,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "BAJFINANCE",
    displayLabel: "Bajaj Finance",
    type: AssetType.stock,
    price: 6900,
    prevPrice: 6900,
    change24h: -1.5,
    isForexRate: false,
  },
  {
    name: "TATAMOTORS",
    displayLabel: "Tata Motors",
    type: AssetType.stock,
    price: 1010,
    prevPrice: 1010,
    change24h: 3.4,
    isForexRate: false,
  },
  {
    name: "TITAN",
    displayLabel: "Titan Company",
    type: AssetType.stock,
    price: 3650,
    prevPrice: 3650,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "SUNPHARMA",
    displayLabel: "Sun Pharma",
    type: AssetType.stock,
    price: 1580,
    prevPrice: 1580,
    change24h: -0.7,
    isForexRate: false,
  },
  {
    name: "ONGC",
    displayLabel: "ONGC",
    type: AssetType.stock,
    price: 265,
    prevPrice: 265,
    change24h: 1.0,
    isForexRate: false,
  },
  {
    name: "POWERGRID",
    displayLabel: "Power Grid Corp",
    type: AssetType.stock,
    price: 320,
    prevPrice: 320,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "NTPC",
    displayLabel: "NTPC",
    type: AssetType.stock,
    price: 345,
    prevPrice: 345,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "COALINDIA",
    displayLabel: "Coal India",
    type: AssetType.stock,
    price: 468,
    prevPrice: 468,
    change24h: 1.2,
    isForexRate: false,
  },
  {
    name: "LTIM",
    displayLabel: "LTIMindtree",
    type: AssetType.stock,
    price: 5450,
    prevPrice: 5450,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "TECHM",
    displayLabel: "Tech Mahindra",
    type: AssetType.stock,
    price: 1320,
    prevPrice: 1320,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "AXISBANK",
    displayLabel: "Axis Bank",
    type: AssetType.stock,
    price: 1120,
    prevPrice: 1120,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "INDUSINDBK",
    displayLabel: "IndusInd Bank",
    type: AssetType.stock,
    price: 1450,
    prevPrice: 1450,
    change24h: -0.4,
    isForexRate: false,
  },
  {
    name: "TATASTEEL",
    displayLabel: "Tata Steel",
    type: AssetType.stock,
    price: 165,
    prevPrice: 165,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "JSWSTEEL",
    displayLabel: "JSW Steel",
    type: AssetType.stock,
    price: 890,
    prevPrice: 890,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "HINDALCO",
    displayLabel: "Hindalco Industries",
    type: AssetType.stock,
    price: 620,
    prevPrice: 620,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "ULTRACEMCO",
    displayLabel: "UltraTech Cement",
    type: AssetType.stock,
    price: 9800,
    prevPrice: 9800,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "GRASIM",
    displayLabel: "Grasim Industries",
    type: AssetType.stock,
    price: 2150,
    prevPrice: 2150,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "DRREDDY",
    displayLabel: "Dr Reddy's Labs",
    type: AssetType.stock,
    price: 6200,
    prevPrice: 6200,
    change24h: -0.5,
    isForexRate: false,
  },
  {
    name: "CIPLA",
    displayLabel: "Cipla",
    type: AssetType.stock,
    price: 1420,
    prevPrice: 1420,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "DIVISLAB",
    displayLabel: "Divi's Laboratories",
    type: AssetType.stock,
    price: 3850,
    prevPrice: 3850,
    change24h: -0.3,
    isForexRate: false,
  },
  {
    name: "APOLLOHOSP",
    displayLabel: "Apollo Hospitals",
    type: AssetType.stock,
    price: 6850,
    prevPrice: 6850,
    change24h: 1.2,
    isForexRate: false,
  },
  {
    name: "EICHERMOT",
    displayLabel: "Eicher Motors",
    type: AssetType.stock,
    price: 4200,
    prevPrice: 4200,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "BAJAJFINSV",
    displayLabel: "Bajaj Finserv",
    type: AssetType.stock,
    price: 1650,
    prevPrice: 1650,
    change24h: -0.8,
    isForexRate: false,
  },
  {
    name: "BPCL",
    displayLabel: "BPCL",
    type: AssetType.stock,
    price: 612,
    prevPrice: 612,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "IOC",
    displayLabel: "Indian Oil Corp",
    type: AssetType.stock,
    price: 168,
    prevPrice: 168,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "HPCL",
    displayLabel: "HPCL",
    type: AssetType.stock,
    price: 382,
    prevPrice: 382,
    change24h: 1.6,
    isForexRate: false,
  },
  {
    name: "TATAPOWER",
    displayLabel: "Tata Power",
    type: AssetType.stock,
    price: 412,
    prevPrice: 412,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "ADANIPORTS",
    displayLabel: "Adani Ports",
    type: AssetType.stock,
    price: 1380,
    prevPrice: 1380,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "ADANIENT",
    displayLabel: "Adani Enterprises",
    type: AssetType.stock,
    price: 2800,
    prevPrice: 2800,
    change24h: -1.2,
    isForexRate: false,
  },
  {
    name: "ADANIPOWER",
    displayLabel: "Adani Power",
    type: AssetType.stock,
    price: 580,
    prevPrice: 580,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "ADANIGREEN",
    displayLabel: "Adani Green Energy",
    type: AssetType.stock,
    price: 1850,
    prevPrice: 1850,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "ADANITRANS",
    displayLabel: "Adani Total Gas",
    type: AssetType.stock,
    price: 620,
    prevPrice: 620,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "DLF",
    displayLabel: "DLF",
    type: AssetType.stock,
    price: 885,
    prevPrice: 885,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "GODREJPROP",
    displayLabel: "Godrej Properties",
    type: AssetType.stock,
    price: 2450,
    prevPrice: 2450,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "OBEROIREAL",
    displayLabel: "Oberoi Realty",
    type: AssetType.stock,
    price: 1620,
    prevPrice: 1620,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "PRESTIGE",
    displayLabel: "Prestige Estates",
    type: AssetType.stock,
    price: 1480,
    prevPrice: 1480,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "ZOMATO",
    displayLabel: "Zomato",
    type: AssetType.stock,
    price: 168,
    prevPrice: 168,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "PAYTM",
    displayLabel: "Paytm (One97)",
    type: AssetType.stock,
    price: 420,
    prevPrice: 420,
    change24h: -0.9,
    isForexRate: false,
  },
  {
    name: "NYKAA",
    displayLabel: "FSN E-Commerce (Nykaa)",
    type: AssetType.stock,
    price: 185,
    prevPrice: 185,
    change24h: 3.1,
    isForexRate: false,
  },
  {
    name: "POLICYBZR",
    displayLabel: "PB Fintech (PolicyBazaar)",
    type: AssetType.stock,
    price: 1250,
    prevPrice: 1250,
    change24h: 4.8,
    isForexRate: false,
  },
  {
    name: "DELHIVERY",
    displayLabel: "Delhivery",
    type: AssetType.stock,
    price: 395,
    prevPrice: 395,
    change24h: 2.7,
    isForexRate: false,
  },
  {
    name: "IXIGO",
    displayLabel: "Le Travenues (Ixigo)",
    type: AssetType.stock,
    price: 215,
    prevPrice: 215,
    change24h: 5.2,
    isForexRate: false,
  },
  {
    name: "IRCTC",
    displayLabel: "IRCTC",
    type: AssetType.stock,
    price: 850,
    prevPrice: 850,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "IRFC",
    displayLabel: "IRFC",
    type: AssetType.stock,
    price: 185,
    prevPrice: 185,
    change24h: 2.3,
    isForexRate: false,
  },
  {
    name: "HAL",
    displayLabel: "Hindustan Aeronautics",
    type: AssetType.stock,
    price: 4250,
    prevPrice: 4250,
    change24h: 3.5,
    isForexRate: false,
  },
  {
    name: "BEL",
    displayLabel: "Bharat Electronics",
    type: AssetType.stock,
    price: 265,
    prevPrice: 265,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "BHEL",
    displayLabel: "Bharat Heavy Electricals",
    type: AssetType.stock,
    price: 248,
    prevPrice: 248,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "MAZAGON",
    displayLabel: "Mazagon Dock",
    type: AssetType.stock,
    price: 3850,
    prevPrice: 3850,
    change24h: 4.1,
    isForexRate: false,
  },
  {
    name: "COCHINSHIP",
    displayLabel: "Cochin Shipyard",
    type: AssetType.stock,
    price: 1620,
    prevPrice: 1620,
    change24h: 3.8,
    isForexRate: false,
  },
  {
    name: "MOTHERSON",
    displayLabel: "Samvardhana Motherson",
    type: AssetType.stock,
    price: 168,
    prevPrice: 168,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "M&M",
    displayLabel: "Mahindra & Mahindra",
    type: AssetType.stock,
    price: 2180,
    prevPrice: 2180,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "HEROMOTOCO",
    displayLabel: "Hero MotoCorp",
    type: AssetType.stock,
    price: 4850,
    prevPrice: 4850,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "BAJAJAUTO",
    displayLabel: "Bajaj Auto",
    type: AssetType.stock,
    price: 9200,
    prevPrice: 9200,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "TVSMOTOR",
    displayLabel: "TVS Motor",
    type: AssetType.stock,
    price: 2350,
    prevPrice: 2350,
    change24h: 1.6,
    isForexRate: false,
  },
  {
    name: "PERSISTENT",
    displayLabel: "Persistent Systems",
    type: AssetType.stock,
    price: 5850,
    prevPrice: 5850,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "MPHASIS",
    displayLabel: "Mphasis",
    type: AssetType.stock,
    price: 2580,
    prevPrice: 2580,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "COFORGE",
    displayLabel: "Coforge",
    type: AssetType.stock,
    price: 6950,
    prevPrice: 6950,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "OFSS",
    displayLabel: "Oracle Financial Services",
    type: AssetType.stock,
    price: 9800,
    prevPrice: 9800,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "KPIT",
    displayLabel: "KPIT Technologies",
    type: AssetType.stock,
    price: 1580,
    prevPrice: 1580,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "LTTS",
    displayLabel: "L&T Technology Services",
    type: AssetType.stock,
    price: 5450,
    prevPrice: 5450,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "TANLA",
    displayLabel: "Tanla Platforms",
    type: AssetType.stock,
    price: 1080,
    prevPrice: 1080,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "RATEGAIN",
    displayLabel: "RateGain Travel",
    type: AssetType.stock,
    price: 780,
    prevPrice: 780,
    change24h: 3.8,
    isForexRate: false,
  },
  {
    name: "IDEAFORGE",
    displayLabel: "ideaForge Technology",
    type: AssetType.stock,
    price: 485,
    prevPrice: 485,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "ASTRAL",
    displayLabel: "Astral",
    type: AssetType.stock,
    price: 2150,
    prevPrice: 2150,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "PIDILITIND",
    displayLabel: "Pidilite Industries",
    type: AssetType.stock,
    price: 2850,
    prevPrice: 2850,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "BERGEPAINT",
    displayLabel: "Berger Paints",
    type: AssetType.stock,
    price: 525,
    prevPrice: 525,
    change24h: -0.4,
    isForexRate: false,
  },
  {
    name: "KANSAINER",
    displayLabel: "Kansai Nerolac Paints",
    type: AssetType.stock,
    price: 295,
    prevPrice: 295,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "HAVELLS",
    displayLabel: "Havells India",
    type: AssetType.stock,
    price: 1620,
    prevPrice: 1620,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "VOLTAS",
    displayLabel: "Voltas",
    type: AssetType.stock,
    price: 1350,
    prevPrice: 1350,
    change24h: 1.2,
    isForexRate: false,
  },
  {
    name: "WHIRLPOOL",
    displayLabel: "Whirlpool of India",
    type: AssetType.stock,
    price: 1480,
    prevPrice: 1480,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "CROMPTON",
    displayLabel: "Crompton Greaves Consumer",
    type: AssetType.stock,
    price: 385,
    prevPrice: 385,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "DIXON",
    displayLabel: "Dixon Technologies",
    type: AssetType.stock,
    price: 8950,
    prevPrice: 8950,
    change24h: 3.4,
    isForexRate: false,
  },
  {
    name: "AMBER",
    displayLabel: "Amber Enterprises",
    type: AssetType.stock,
    price: 3850,
    prevPrice: 3850,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "CAMPUS",
    displayLabel: "Campus Activewear",
    type: AssetType.stock,
    price: 285,
    prevPrice: 285,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "BATA",
    displayLabel: "Bata India",
    type: AssetType.stock,
    price: 1420,
    prevPrice: 1420,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "RELAXO",
    displayLabel: "Relaxo Footwears",
    type: AssetType.stock,
    price: 780,
    prevPrice: 780,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "PAGEIND",
    displayLabel: "Page Industries (Jockey)",
    type: AssetType.stock,
    price: 42000,
    prevPrice: 42000,
    change24h: 0.3,
    isForexRate: false,
  },
  {
    name: "MANYAVAR",
    displayLabel: "Vedant Fashions (Manyavar)",
    type: AssetType.stock,
    price: 1180,
    prevPrice: 1180,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "TRENT",
    displayLabel: "Trent (Westside)",
    type: AssetType.stock,
    price: 4850,
    prevPrice: 4850,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "SHOPPERSS",
    displayLabel: "Shoppers Stop",
    type: AssetType.stock,
    price: 825,
    prevPrice: 825,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "DMART",
    displayLabel: "Avenue Supermarts (D-Mart)",
    type: AssetType.stock,
    price: 4250,
    prevPrice: 4250,
    change24h: -0.6,
    isForexRate: false,
  },
  {
    name: "VSTIND",
    displayLabel: "VST Industries",
    type: AssetType.stock,
    price: 3650,
    prevPrice: 3650,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "MARICO",
    displayLabel: "Marico",
    type: AssetType.stock,
    price: 625,
    prevPrice: 625,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "DABUR",
    displayLabel: "Dabur India",
    type: AssetType.stock,
    price: 560,
    prevPrice: 560,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "GODREJCP",
    displayLabel: "Godrej Consumer Products",
    type: AssetType.stock,
    price: 1250,
    prevPrice: 1250,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "EMAMILTD",
    displayLabel: "Emami",
    type: AssetType.stock,
    price: 625,
    prevPrice: 625,
    change24h: 1.2,
    isForexRate: false,
  },
  {
    name: "ITC",
    displayLabel: "ITC",
    type: AssetType.stock,
    price: 435,
    prevPrice: 435,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "NESTLEIND",
    displayLabel: "Nestle India",
    type: AssetType.stock,
    price: 2450,
    prevPrice: 2450,
    change24h: -0.3,
    isForexRate: false,
  },
  {
    name: "BRITANNIA",
    displayLabel: "Britannia Industries",
    type: AssetType.stock,
    price: 5200,
    prevPrice: 5200,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "TATACONSUM",
    displayLabel: "Tata Consumer Products",
    type: AssetType.stock,
    price: 1080,
    prevPrice: 1080,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "ZYDUSLIFE",
    displayLabel: "Zydus Lifesciences",
    type: AssetType.stock,
    price: 1020,
    prevPrice: 1020,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "LUPIN",
    displayLabel: "Lupin",
    type: AssetType.stock,
    price: 1680,
    prevPrice: 1680,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "AUROPHARMA",
    displayLabel: "Aurobindo Pharma",
    type: AssetType.stock,
    price: 1120,
    prevPrice: 1120,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "TORNTPHARM",
    displayLabel: "Torrent Pharmaceuticals",
    type: AssetType.stock,
    price: 2850,
    prevPrice: 2850,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "ABBOTINDIA",
    displayLabel: "Abbott India",
    type: AssetType.stock,
    price: 26500,
    prevPrice: 26500,
    change24h: 0.3,
    isForexRate: false,
  },
  {
    name: "PFIZER",
    displayLabel: "Pfizer India",
    type: AssetType.stock,
    price: 4850,
    prevPrice: 4850,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "SANOFI",
    displayLabel: "Sanofi India",
    type: AssetType.stock,
    price: 8200,
    prevPrice: 8200,
    change24h: 0.2,
    isForexRate: false,
  },
  {
    name: "ICICIGI",
    displayLabel: "ICICI Lombard General Ins",
    type: AssetType.stock,
    price: 1780,
    prevPrice: 1780,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "HDFCLIFE",
    displayLabel: "HDFC Life Insurance",
    type: AssetType.stock,
    price: 625,
    prevPrice: 625,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "SBILIFE",
    displayLabel: "SBI Life Insurance",
    type: AssetType.stock,
    price: 1580,
    prevPrice: 1580,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "LICI",
    displayLabel: "LIC of India",
    type: AssetType.stock,
    price: 1020,
    prevPrice: 1020,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "STARHEALTH",
    displayLabel: "Star Health Insurance",
    type: AssetType.stock,
    price: 580,
    prevPrice: 580,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "MUTHOOTFIN",
    displayLabel: "Muthoot Finance",
    type: AssetType.stock,
    price: 1820,
    prevPrice: 1820,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "MANAPPURAM",
    displayLabel: "Manappuram Finance",
    type: AssetType.stock,
    price: 185,
    prevPrice: 185,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "SHRIRAMFIN",
    displayLabel: "Shriram Finance",
    type: AssetType.stock,
    price: 2480,
    prevPrice: 2480,
    change24h: 1.2,
    isForexRate: false,
  },
  {
    name: "CHOLAFIN",
    displayLabel: "Cholamandalam Invest",
    type: AssetType.stock,
    price: 1280,
    prevPrice: 1280,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "M&MFIN",
    displayLabel: "M&M Financial Services",
    type: AssetType.stock,
    price: 285,
    prevPrice: 285,
    change24h: 1.6,
    isForexRate: false,
  },
  {
    name: "RECLTD",
    displayLabel: "REC Ltd",
    type: AssetType.stock,
    price: 565,
    prevPrice: 565,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "PFC",
    displayLabel: "Power Finance Corp",
    type: AssetType.stock,
    price: 480,
    prevPrice: 480,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "HUDCO",
    displayLabel: "HUDCO",
    type: AssetType.stock,
    price: 248,
    prevPrice: 248,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "IDFCFIRSTB",
    displayLabel: "IDFC First Bank",
    type: AssetType.stock,
    price: 82,
    prevPrice: 82,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "BANDHANBNK",
    displayLabel: "Bandhan Bank",
    type: AssetType.stock,
    price: 195,
    prevPrice: 195,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "FEDERALBNK",
    displayLabel: "Federal Bank",
    type: AssetType.stock,
    price: 168,
    prevPrice: 168,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "RBLBANK",
    displayLabel: "RBL Bank",
    type: AssetType.stock,
    price: 215,
    prevPrice: 215,
    change24h: -0.8,
    isForexRate: false,
  },
  {
    name: "YESBANK",
    displayLabel: "Yes Bank",
    type: AssetType.stock,
    price: 22.5,
    prevPrice: 22.5,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "PNB",
    displayLabel: "Punjab National Bank",
    type: AssetType.stock,
    price: 118,
    prevPrice: 118,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "BANKBARODA",
    displayLabel: "Bank of Baroda",
    type: AssetType.stock,
    price: 248,
    prevPrice: 248,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "CANBK",
    displayLabel: "Canara Bank",
    type: AssetType.stock,
    price: 105,
    prevPrice: 105,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "UNIONBANK",
    displayLabel: "Union Bank of India",
    type: AssetType.stock,
    price: 138,
    prevPrice: 138,
    change24h: 2.2,
    isForexRate: false,
  },
  {
    name: "IOB",
    displayLabel: "Indian Overseas Bank",
    type: AssetType.stock,
    price: 62,
    prevPrice: 62,
    change24h: 2.5,
    isForexRate: false,
  },
  {
    name: "CENTRALBK",
    displayLabel: "Central Bank of India",
    type: AssetType.stock,
    price: 58,
    prevPrice: 58,
    change24h: 2.8,
    isForexRate: false,
  },
  // US Stocks (available on Groww)
  {
    name: "AAPL",
    displayLabel: "Apple Inc.",
    type: AssetType.stock,
    price: 178,
    prevPrice: 178,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "MSFT",
    displayLabel: "Microsoft Corp.",
    type: AssetType.stock,
    price: 415,
    prevPrice: 415,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "GOOGL",
    displayLabel: "Alphabet (Google)",
    type: AssetType.stock,
    price: 168,
    prevPrice: 168,
    change24h: -0.2,
    isForexRate: false,
  },
  {
    name: "AMZN",
    displayLabel: "Amazon",
    type: AssetType.stock,
    price: 185,
    prevPrice: 185,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "TSLA",
    displayLabel: "Tesla",
    type: AssetType.stock,
    price: 177,
    prevPrice: 177,
    change24h: -2.3,
    isForexRate: false,
  },
  {
    name: "NVDA",
    displayLabel: "Nvidia",
    type: AssetType.stock,
    price: 875,
    prevPrice: 875,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "META",
    displayLabel: "Meta Platforms",
    type: AssetType.stock,
    price: 495,
    prevPrice: 495,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "BRK.B",
    displayLabel: "Berkshire Hathaway",
    type: AssetType.stock,
    price: 400,
    prevPrice: 400,
    change24h: 0.3,
    isForexRate: false,
  },
  {
    name: "V",
    displayLabel: "Visa Inc.",
    type: AssetType.stock,
    price: 276,
    prevPrice: 276,
    change24h: 0.1,
    isForexRate: false,
  },
  {
    name: "JPM",
    displayLabel: "JPMorgan Chase",
    type: AssetType.stock,
    price: 195,
    prevPrice: 195,
    change24h: -0.4,
    isForexRate: false,
  },
  {
    name: "NFLX",
    displayLabel: "Netflix",
    type: AssetType.stock,
    price: 620,
    prevPrice: 620,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "BABA",
    displayLabel: "Alibaba Group",
    type: AssetType.stock,
    price: 72,
    prevPrice: 72,
    change24h: -1.8,
    isForexRate: false,
  },
  {
    name: "TSM",
    displayLabel: "TSMC",
    type: AssetType.stock,
    price: 145,
    prevPrice: 145,
    change24h: 2.0,
    isForexRate: false,
  },
  {
    name: "AMD",
    displayLabel: "AMD",
    type: AssetType.stock,
    price: 175,
    prevPrice: 175,
    change24h: 2.8,
    isForexRate: false,
  },
  {
    name: "INTC",
    displayLabel: "Intel Corporation",
    type: AssetType.stock,
    price: 35,
    prevPrice: 35,
    change24h: -0.9,
    isForexRate: false,
  },
  {
    name: "QCOM",
    displayLabel: "Qualcomm",
    type: AssetType.stock,
    price: 168,
    prevPrice: 168,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "AVGO",
    displayLabel: "Broadcom",
    type: AssetType.stock,
    price: 1420,
    prevPrice: 1420,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "ORCL",
    displayLabel: "Oracle Corp.",
    type: AssetType.stock,
    price: 128,
    prevPrice: 128,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "CRM",
    displayLabel: "Salesforce",
    type: AssetType.stock,
    price: 295,
    prevPrice: 295,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "ADBE",
    displayLabel: "Adobe Inc.",
    type: AssetType.stock,
    price: 475,
    prevPrice: 475,
    change24h: -0.5,
    isForexRate: false,
  },
  {
    name: "PYPL",
    displayLabel: "PayPal Holdings",
    type: AssetType.stock,
    price: 62,
    prevPrice: 62,
    change24h: -1.2,
    isForexRate: false,
  },
  {
    name: "DIS",
    displayLabel: "Walt Disney",
    type: AssetType.stock,
    price: 112,
    prevPrice: 112,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "SPOT",
    displayLabel: "Spotify",
    type: AssetType.stock,
    price: 285,
    prevPrice: 285,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "UBER",
    displayLabel: "Uber Technologies",
    type: AssetType.stock,
    price: 72,
    prevPrice: 72,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "LYFT",
    displayLabel: "Lyft",
    type: AssetType.stock,
    price: 18,
    prevPrice: 18,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "ABNB",
    displayLabel: "Airbnb",
    type: AssetType.stock,
    price: 152,
    prevPrice: 152,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "COIN",
    displayLabel: "Coinbase Global",
    type: AssetType.stock,
    price: 225,
    prevPrice: 225,
    change24h: 5.2,
    isForexRate: false,
  },
  {
    name: "HOOD",
    displayLabel: "Robinhood Markets",
    type: AssetType.stock,
    price: 18,
    prevPrice: 18,
    change24h: 3.8,
    isForexRate: false,
  },
  {
    name: "SQ",
    displayLabel: "Block Inc. (Square)",
    type: AssetType.stock,
    price: 72,
    prevPrice: 72,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "SOFI",
    displayLabel: "SoFi Technologies",
    type: AssetType.stock,
    price: 8.5,
    prevPrice: 8.5,
    change24h: 3.2,
    isForexRate: false,
  },
  {
    name: "MSTR",
    displayLabel: "MicroStrategy",
    type: AssetType.stock,
    price: 1250,
    prevPrice: 1250,
    change24h: 8.5,
    isForexRate: false,
  },
  {
    name: "RIVN",
    displayLabel: "Rivian Automotive",
    type: AssetType.stock,
    price: 12.5,
    prevPrice: 12.5,
    change24h: -1.8,
    isForexRate: false,
  },
  {
    name: "LCID",
    displayLabel: "Lucid Group",
    type: AssetType.stock,
    price: 2.85,
    prevPrice: 2.85,
    change24h: -2.4,
    isForexRate: false,
  },
  {
    name: "NIO",
    displayLabel: "NIO Inc.",
    type: AssetType.stock,
    price: 5.2,
    prevPrice: 5.2,
    change24h: -3.1,
    isForexRate: false,
  },
  {
    name: "XPEV",
    displayLabel: "XPeng Inc.",
    type: AssetType.stock,
    price: 9.8,
    prevPrice: 9.8,
    change24h: -2.7,
    isForexRate: false,
  },
  {
    name: "LI",
    displayLabel: "Li Auto",
    type: AssetType.stock,
    price: 22,
    prevPrice: 22,
    change24h: -1.5,
    isForexRate: false,
  },
  {
    name: "PLTR",
    displayLabel: "Palantir Technologies",
    type: AssetType.stock,
    price: 25,
    prevPrice: 25,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "AI",
    displayLabel: "C3.ai",
    type: AssetType.stock,
    price: 28,
    prevPrice: 28,
    change24h: 5.8,
    isForexRate: false,
  },
  {
    name: "PATH",
    displayLabel: "UiPath",
    type: AssetType.stock,
    price: 14,
    prevPrice: 14,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "SNOW",
    displayLabel: "Snowflake",
    type: AssetType.stock,
    price: 145,
    prevPrice: 145,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "ZS",
    displayLabel: "Zscaler",
    type: AssetType.stock,
    price: 195,
    prevPrice: 195,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "CRWD",
    displayLabel: "CrowdStrike",
    type: AssetType.stock,
    price: 325,
    prevPrice: 325,
    change24h: 2.4,
    isForexRate: false,
  },
  {
    name: "PANW",
    displayLabel: "Palo Alto Networks",
    type: AssetType.stock,
    price: 285,
    prevPrice: 285,
    change24h: 1.9,
    isForexRate: false,
  },
  {
    name: "SPY",
    displayLabel: "SPDR S&P 500 ETF",
    type: AssetType.stock,
    price: 525,
    prevPrice: 525,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "QQQ",
    displayLabel: "Invesco QQQ (NASDAQ)",
    type: AssetType.stock,
    price: 448,
    prevPrice: 448,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "GLD",
    displayLabel: "SPDR Gold Shares ETF",
    type: AssetType.stock,
    price: 215,
    prevPrice: 215,
    change24h: 0.5,
    isForexRate: false,
  },

  // ── INDIAN PENNY / LOW-PRICE STOCKS (₹10–₹50 range) ─────────────────────
  {
    name: "SUZLON",
    displayLabel: "Suzlon Energy",
    type: AssetType.stock,
    price: 43,
    prevPrice: 43,
    change24h: 2.1,
    isForexRate: false,
  },
  {
    name: "YESBANK",
    displayLabel: "Yes Bank",
    type: AssetType.stock,
    price: 22,
    prevPrice: 22,
    change24h: -1.4,
    isForexRate: false,
  },
  {
    name: "IDEA",
    displayLabel: "Vodafone Idea (Vi)",
    type: AssetType.stock,
    price: 12,
    prevPrice: 12,
    change24h: 3.5,
    isForexRate: false,
  },
  {
    name: "ALOKIND",
    displayLabel: "Alok Industries",
    type: AssetType.stock,
    price: 22,
    prevPrice: 22,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "TRIDENT",
    displayLabel: "Trident Ltd",
    type: AssetType.stock,
    price: 38,
    prevPrice: 38,
    change24h: 1.3,
    isForexRate: false,
  },
  {
    name: "SOUTHBANK",
    displayLabel: "South Indian Bank",
    type: AssetType.stock,
    price: 25,
    prevPrice: 25,
    change24h: -0.7,
    isForexRate: false,
  },
  {
    name: "CENTRALBK",
    displayLabel: "Central Bank of India",
    type: AssetType.stock,
    price: 48,
    prevPrice: 48,
    change24h: 1.0,
    isForexRate: false,
  },
  {
    name: "PUNJABNB",
    displayLabel: "Punjab & Sind Bank",
    type: AssetType.stock,
    price: 45,
    prevPrice: 45,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "UCOBANK",
    displayLabel: "UCO Bank",
    type: AssetType.stock,
    price: 48,
    prevPrice: 48,
    change24h: 2.2,
    isForexRate: false,
  },
  {
    name: "RPOWER",
    displayLabel: "Reliance Power",
    type: AssetType.stock,
    price: 30,
    prevPrice: 30,
    change24h: -2.8,
    isForexRate: false,
  },
  {
    name: "JPPOWER",
    displayLabel: "Jaiprakash Power",
    type: AssetType.stock,
    price: 17,
    prevPrice: 17,
    change24h: 1.6,
    isForexRate: false,
  },
  {
    name: "RENUKA",
    displayLabel: "Shree Renuka Sugars",
    type: AssetType.stock,
    price: 47,
    prevPrice: 47,
    change24h: 0.3,
    isForexRate: false,
  },
  {
    name: "SPICEJET",
    displayLabel: "SpiceJet",
    type: AssetType.stock,
    price: 48,
    prevPrice: 48,
    change24h: -1.9,
    isForexRate: false,
  },
  {
    name: "DISHTV",
    displayLabel: "Dish TV India",
    type: AssetType.stock,
    price: 15,
    prevPrice: 15,
    change24h: 0.7,
    isForexRate: false,
  },
  {
    name: "JETAIRWAYS",
    displayLabel: "Jet Airways",
    type: AssetType.stock,
    price: 50,
    prevPrice: 50,
    change24h: -0.5,
    isForexRate: false,
  },
  {
    name: "GMRINFRA",
    displayLabel: "GMR Airports Infra",
    type: AssetType.stock,
    price: 42,
    prevPrice: 42,
    change24h: 1.8,
    isForexRate: false,
  },
  {
    name: "RTNPOWER",
    displayLabel: "RattanIndia Power",
    type: AssetType.stock,
    price: 18,
    prevPrice: 18,
    change24h: 4.2,
    isForexRate: false,
  },
  {
    name: "JPASSOCIAT",
    displayLabel: "Jaiprakash Associates",
    type: AssetType.stock,
    price: 11,
    prevPrice: 11,
    change24h: -3.1,
    isForexRate: false,
  },
  {
    name: "GTLINFRA",
    displayLabel: "GTL Infrastructure",
    type: AssetType.stock,
    price: 3,
    prevPrice: 3,
    change24h: 1.0,
    isForexRate: false,
  },
  {
    name: "LOTTEINDIA",
    displayLabel: "Lotte India",
    type: AssetType.stock,
    price: 35,
    prevPrice: 35,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "KPITTECH",
    displayLabel: "KPIT Technologies (small)",
    type: AssetType.stock,
    price: 40,
    prevPrice: 40,
    change24h: 2.0,
    isForexRate: false,
  },
  {
    name: "ANDHRABANK",
    displayLabel: "Andhra Bank (merged)",
    type: AssetType.stock,
    price: 28,
    prevPrice: 28,
    change24h: 0.4,
    isForexRate: false,
  },
  {
    name: "CORPBANK",
    displayLabel: "Corporation Bank (merged)",
    type: AssetType.stock,
    price: 32,
    prevPrice: 32,
    change24h: 0.2,
    isForexRate: false,
  },
  {
    name: "PRAJIND",
    displayLabel: "Praj Industries",
    type: AssetType.stock,
    price: 46,
    prevPrice: 46,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "ARSSINFRA",
    displayLabel: "ARSS Infrastructure",
    type: AssetType.stock,
    price: 20,
    prevPrice: 20,
    change24h: -0.9,
    isForexRate: false,
  },
  {
    name: "HERITGFOOD",
    displayLabel: "Heritage Foods",
    type: AssetType.stock,
    price: 36,
    prevPrice: 36,
    change24h: 0.8,
    isForexRate: false,
  },
  {
    name: "ORIENTCER",
    displayLabel: "Orient Cement",
    type: AssetType.stock,
    price: 27,
    prevPrice: 27,
    change24h: 1.5,
    isForexRate: false,
  },
  {
    name: "KELTONENRG",
    displayLabel: "Keltone Energy",
    type: AssetType.stock,
    price: 14,
    prevPrice: 14,
    change24h: 2.3,
    isForexRate: false,
  },
  {
    name: "PCJEWELLER",
    displayLabel: "PC Jeweller",
    type: AssetType.stock,
    price: 26,
    prevPrice: 26,
    change24h: -1.2,
    isForexRate: false,
  },
  {
    name: "RAILVIKAS",
    displayLabel: "Rail Vikas Nigam",
    type: AssetType.stock,
    price: 45,
    prevPrice: 45,
    change24h: 1.7,
    isForexRate: false,
  },
  {
    name: "MANAPPURAM",
    displayLabel: "Manappuram Finance",
    type: AssetType.stock,
    price: 195,
    prevPrice: 195,
    change24h: 0.9,
    isForexRate: false,
  },
  {
    name: "NIACL",
    displayLabel: "New India Assurance",
    type: AssetType.stock,
    price: 210,
    prevPrice: 210,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "SCINDIA",
    displayLabel: "Shipping Corp India",
    type: AssetType.stock,
    price: 185,
    prevPrice: 185,
    change24h: 1.4,
    isForexRate: false,
  },
  {
    name: "TNPL",
    displayLabel: "Tamil Nadu Newsprint",
    type: AssetType.stock,
    price: 430,
    prevPrice: 430,
    change24h: 0.3,
    isForexRate: false,
  },
  {
    name: "UJJIVANSFB",
    displayLabel: "Ujjivan Small Finance Bank",
    type: AssetType.stock,
    price: 38,
    prevPrice: 38,
    change24h: 2.5,
    isForexRate: false,
  },
  {
    name: "ESAFSFB",
    displayLabel: "ESAF Small Finance Bank",
    type: AssetType.stock,
    price: 50,
    prevPrice: 50,
    change24h: 1.1,
    isForexRate: false,
  },
  {
    name: "EQUITASBNK",
    displayLabel: "Equitas Small Finance Bank",
    type: AssetType.stock,
    price: 82,
    prevPrice: 82,
    change24h: 0.6,
    isForexRate: false,
  },
  {
    name: "UTTAMSUGAR",
    displayLabel: "Uttam Sugar Mills",
    type: AssetType.stock,
    price: 29,
    prevPrice: 29,
    change24h: -0.4,
    isForexRate: false,
  },
  {
    name: "DCMSHRIRAM",
    displayLabel: "DCM Shriram",
    type: AssetType.stock,
    price: 10,
    prevPrice: 10,
    change24h: 0.5,
    isForexRate: false,
  },
  {
    name: "GANGAGEN",
    displayLabel: "GangaGen (Biotech)",
    type: AssetType.stock,
    price: 13,
    prevPrice: 13,
    change24h: 3.0,
    isForexRate: false,
  },
  {
    name: "JTEKTINDIA",
    displayLabel: "JTEKT India",
    type: AssetType.stock,
    price: 47,
    prevPrice: 47,
    change24h: 0.8,
    isForexRate: false,
  },
];

interface MarketContextValue {
  assets: MarketAsset[];
  getPrice: (name: string) => number;
}

const MarketContext = createContext<MarketContextValue | undefined>(undefined);

function useMarketDataInternal(): MarketContextValue {
  const [assets, setAssets] = useState<MarketAsset[]>(SEED);

  useEffect(() => {
    const id = setInterval(() => {
      setAssets((prev) =>
        prev.map((a) => {
          const delta = (Math.random() - 0.5) * 0.005 * a.price;
          const newPrice = Math.max(0.0000001, a.price + delta);
          const dailyDelta = (Math.random() - 0.5) * 0.08;
          return {
            ...a,
            prevPrice: a.price,
            price: newPrice,
            change24h: Math.max(-20, Math.min(20, a.change24h + dailyDelta)),
          };
        }),
      );
    }, 3000);
    return () => clearInterval(id);
  }, []);

  const getPrice = (name: string): number =>
    assets.find((a) => a.name === name)?.price ?? 0;

  return { assets, getPrice };
}

export function MarketDataProvider({ children }: { children: ReactNode }) {
  const value = useMarketDataInternal();
  return createElement(MarketContext.Provider, { value, children });
}

export function useMarketData(): MarketContextValue {
  const ctx = useContext(MarketContext);
  if (!ctx) throw new Error("MarketDataProvider not found");
  return ctx;
}
