/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssetData {
  'name' : string,
  'assetType' : AssetType,
  'price' : number,
}
export type AssetType = { 'forex' : null } |
  { 'stock' : null } |
  { 'crypto' : null };
export type KYCStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'banned' : null } |
  { 'unverified' : null };
export interface PortfolioView {
  'totalValue' : number,
  'holdings' : Array<[string, number]>,
}
export interface Trade {
  'asset' : string,
  'tradeType' : { 'buy' : null } |
    { 'sell' : null },
  'timestamp' : bigint,
  'assetType' : AssetType,
  'price' : number,
  'amount' : number,
}
export interface UserProfile {
  'age' : bigint,
  'trialEndTime' : [] | [bigint],
  'name' : string,
  'email' : string,
  'kycStatus' : KYCStatus,
  'panMock' : string,
  'aadhaarMock' : string,
  'mobile' : string,
  'registrationTime' : bigint,
  'isTaxFree' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkTrialStatus' : ActorMethod<[Principal], boolean>,
  'getAllAssetPrices' : ActorMethod<[], Array<AssetData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolio' : ActorMethod<[Principal], PortfolioView>,
  'getTradeHistory' : ActorMethod<[Principal], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeTrade' : ActorMethod<
    [string, AssetType, { 'buy' : null } | { 'sell' : null }, number],
    undefined
  >,
  'registerUser' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAssetPrice' : ActorMethod<[string, AssetType, number], undefined>,
  'updateKYCStatus' : ActorMethod<[Principal, KYCStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];