/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetType = IDL.Variant({
  'forex' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const AssetData = IDL.Record({
  'name' : IDL.Text,
  'assetType' : AssetType,
  'price' : IDL.Float64,
});
export const KYCStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'banned' : IDL.Null,
  'unverified' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'trialEndTime' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'kycStatus' : KYCStatus,
  'panMock' : IDL.Text,
  'aadhaarMock' : IDL.Text,
  'mobile' : IDL.Text,
  'registrationTime' : IDL.Int,
  'isTaxFree' : IDL.Bool,
});
export const PortfolioView = IDL.Record({
  'totalValue' : IDL.Float64,
  'holdings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const Trade = IDL.Record({
  'asset' : IDL.Text,
  'tradeType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'timestamp' : IDL.Int,
  'assetType' : AssetType,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkTrialStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getAllAssetPrices' : IDL.Func([], [IDL.Vec(AssetData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolio' : IDL.Func([IDL.Principal], [PortfolioView], ['query']),
  'getTradeHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeTrade' : IDL.Func(
      [
        IDL.Text,
        AssetType,
        IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
        IDL.Float64,
      ],
      [],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAssetPrice' : IDL.Func([IDL.Text, AssetType, IDL.Float64], [], []),
  'updateKYCStatus' : IDL.Func([IDL.Principal, KYCStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetType = IDL.Variant({
    'forex' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const AssetData = IDL.Record({
    'name' : IDL.Text,
    'assetType' : AssetType,
    'price' : IDL.Float64,
  });
  const KYCStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'banned' : IDL.Null,
    'unverified' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'trialEndTime' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'kycStatus' : KYCStatus,
    'panMock' : IDL.Text,
    'aadhaarMock' : IDL.Text,
    'mobile' : IDL.Text,
    'registrationTime' : IDL.Int,
    'isTaxFree' : IDL.Bool,
  });
  const PortfolioView = IDL.Record({
    'totalValue' : IDL.Float64,
    'holdings' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const Trade = IDL.Record({
    'asset' : IDL.Text,
    'tradeType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'timestamp' : IDL.Int,
    'assetType' : AssetType,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkTrialStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'getAllAssetPrices' : IDL.Func([], [IDL.Vec(AssetData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolio' : IDL.Func([IDL.Principal], [PortfolioView], ['query']),
    'getTradeHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeTrade' : IDL.Func(
        [
          IDL.Text,
          AssetType,
          IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
          IDL.Float64,
        ],
        [],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAssetPrice' : IDL.Func([IDL.Text, AssetType, IDL.Float64], [], []),
    'updateKYCStatus' : IDL.Func([IDL.Principal, KYCStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };